version: '2'


services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8001
        --access-logfile -
        --reload
        "book_api.app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/book_api'
    ports:
      - '8000:8001'
